# Task: 30-day Readmission Risk Prediction
predicates:
  admission:
    code: ADMIT_DATE
  discharge:
    code: DISCHARGE_DATE

trigger: admission

windows:
  input:
    start: trigger
    end: start -> discharge
    start_inclusive: False
    end_inclusive: True
  target:
    start: input.end
    end: start + 30 days
    start_inclusive: False
    end_inclusive: True
    label: admission
