# User inputs
code_metadata_fp: ${MEDS_cohort_dir}/code_metadata.parquet
allowed_codes: null
min_code_inclusion_frequency: 10
window_sizes:
  - "1d"
  - "7d"
  - "30d"
  - "365d"
  - "full"
aggs:
  - "static/present"
  - "static/first"
  - "code/count"
  - "value/count"
  - "value/sum"
  - "value/sum_sqd"
  - "value/min"
  - "value/max"

# Resolved inputs
_resolved_codes: ${filter_to_codes:${allowed_codes},${min_code_inclusion_frequency},${code_metadata_fp}}
