# @package _global_

defaults:
  - default
  - training_params: default
  - _self_

model_launcher:
  _target_: MEDS_tabular_automl.sklearn_model.SklearnModel.initialize

  model:
    _target_: sklearn.neighbors.KNeighborsClassifier
    weights: "distance"
    leaf_size: 30
    p: 2
    metric: "minkowski"

  path:
    model_file_extension: .pkl

hydra:
  sweeper:
    params:
      model.n_neighbors: range(1, 20)
      model.weights: choice(['uniform', 'distance'])
      model.leaf_size: range(10, 50)
      model.p: choice([1, 2])
      model.metric: choice(['minkowski', 'euclidean', 'manhattan'])
      epochs: range(10, 100)
      early_stopping_rounds: range(1, 10)
