defaults:
  - default
  - hydra/sweeper: default
  - _self_

_target_: MEDS_tabular_automl.sklearn_model.SklearnModel.initialize

model:
  _target_: sklearn.linear_model.LogisticRegression
  penalty: "l2"
  dual: false
  tol: 0.0001
  C: 1.0
  fit_intercept: True
  intercept_scaling: 1
  class_weight: null
  random_state: null
  solver: "lbfgs"
  max_iter: 100

training_params:
  epochs: 20
  early_stopping_rounds: 5

path:
  model_file_extension: .pkl

hydra:
  sweeper:
    +params:
      model.C: tag(log, interval(1e-6, 1))
      model.penalty: choice(['l1', 'l2', 'elasticnet'])
      model.solver: choice(['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'])
      epochs: range(10, 100)
      early_stopping_rounds: range(1, 10)
