defaults:
  - default
  - hydra/sweeper: default
  - _self_

_target_: MEDS_tabular_automl.sklearn_model.SklearnModel.initialize

model:
  _target_: sklearn.ensemble.RandomForestClassifier
  criterion: "gini"
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: "sqrt"
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  bootstrap: True

training_params:
  epochs: 20
  early_stopping_rounds: 5

path:
  model_file_extension: .pkl

hydra:
  sweeper:
    +params:
      model.n_estimators: range(50, 300, 50)
      model.max_depth: choice([null, 10, 20, 30, 40, 50])
      model.min_samples_split: range(2, 11)
      model.min_samples_leaf: range(1, 5)
      model.max_features: choice(['sqrt', 'log2', null])
      model.bootstrap: choice([True, False])
      model.criterion: choice(['gini', 'entropy'])
      epochs: range(10, 100)
      early_stopping_rounds: range(1, 10)
