defaults:
  - default
  - hydra/sweeper: default
  - _self_

_target_: MEDS_tabular_automl.xgboost_model.XGBoostModel.initialize

model:
  booster: gbtree
  device: cpu
  nthread: 1
  tree_method: hist
  objective: binary:logistic

training_params:
  num_boost_round: 1000
  early_stopping_rounds: 5

hydra:
  sweeper:
    +params:
      model.eta: tag(log, interval(0.001, 1))
      model.lambda: tag(log, interval(0.001, 1))
      model.alpha: tag(log, interval(0.001, 1))
      model.subsample: interval(0.5, 1)
      model.min_child_weight: interval(1e-2, 100)
      num_boost_round: range(100, 1000)
      early_stopping_rounds: range(1, 10)
      model.max_depth: range(2, 16)
      tabularization.min_code_inclusion_frequency: tag(log, range(10, 1000000))
