# Raw data
MEDS_cohort_dir: ???
tabularized_data_dir: ${MEDS_cohort_dir}/tabularize
task_dir: ${tabularized_data_dir}/task
model_dir: ${MEDS_cohort_dir}/model/${now:%Y-%m-%d_%H-%M-%S}
cache_dir: ${tabularized_data_dir}/.cache

# Pre-processing
min_code_inclusion_frequency: 1
window_sizes:
  - "1d"
  - "7d"
  - "30d"
  - "365d"
  - "full"
codes: null
aggs:
  - "static/present"
  - "static/first"
  - "code/count"
  - "value/count"
  - "value/sum"
  - "value/sum_sqd"
  - "value/min"
  - "value/max"

dynamic_threshold: 0.01
numerical_value_threshold: 0.1

# Sharding
n_patients_per_sub_shard: null

# Misc
do_overwrite: False
seed: 1
tqdm: False
worker: 1
loguru_init: False

# Hydra
hydra:
  job:
    name: tabularize_step_${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: ${tabularized_data_dir}/.logs/etl/${hydra.job.name}
  sweep:
    dir: ${tabularized_data_dir}/.logs/etl/${hydra.job.name}




Describe codes:
MEDS_cohort_dir: ???
tabularized_data_dir: ${MEDS_cohort_dir}/tabularize
feature_path: ${tabularized_data_dir}/feature_description.parquet

Final inputs:
MEDS final cohort directory (see tabularization)
Output filepath

User inputs:
MEDS Base Directory
-> ... see tabularization

Output: Dataframe with a column “code” and a column “code/n_occurrences”

Tabularization:
static is fast
multirun only for time series

Final inputs:
MEDS final cohort directory (directory within which there are shard keys and MEDS formatted files for tabularization)
Tabularization parameters (see above)

User inputs:
Tabularizaton parameters
MEDS Base Directory
-> MEDS final cohort directory via final_cohort subdir or something
-> code metadata file via code_metadata.parquet file
Task-specific Caching
Final inputs:
Task directory: In the config file, somehow, specify a filepath to a directory which contains, in the same shard keys (e.g., “train/0”, “prospective_test_set/2”) parquet files with patient_id, index_datetime, and label). index_datetime is assumed to be inclusive but there is a configuration parameter that controls this. 
Full tabularized data directory: directory within which there are shard keys mapping to tabularized sparse matrices.

User inputs:
MEDS Base Directory
Task name
XGBoost:
Final Inputs:
Tabular feature selection parameters (see above)
Final task specific cached data directory.
XGBoost Model Parameters
In memory vs. external memory.

User Inputs:
MEDS Base Directory
Task name
