defaults:
  - default
  - tabularization: default
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - _self_

# Raw data
MEDS_cohort_dir: ???
input_directory: ${MEDS_cohort_dir}/task
# Where to output the model and cached data
output_dir: ${MEDS_cohort_dir}/model/model_${now:%Y-%m-%d_%H-%M-%S}
output_filepath: ${output_dir}/model_metadata.parquet
cache_dir: ${MEDS_cohort_dir}/.cache

# Model parameters
model_params:
  num_boost_round: 1000
  early_stopping_rounds: 5
  model:
    booster: gbtree
    device: cpu
    tree_method: hist
    objective: binary:logistic
  iterator:
    keep_data_in_memory: False
    binarize_task: True

# Sweep parameters for Optuna
hydra:
  # Optuna Sweeper
  sweeper:
    sampler:
      seed: 1
    storage: null
    study_name: tabularize_study_${now:%Y-%m-%d_%H-%M-%S}
    direction: minimize
    n_trials: 10

    # Define search space for Optuna
    params:
      window_sizes:
        _target_: hydra.utils.call(${hydra.utils.cross_product},
          values=["1d", "7d", "30d", "365d", "full"]) # , max_options=5)
      iterator.keep_data_in_memory: choice([True], [False])
