# Raw data
MEDS_cohort_dir: ???
tabularized_data_dir: ???

# Pre-processing
min_code_inclusion_frequency: ???
window_sizes: ???
codes: null
aggs:
  - "code/count"
  - "code/present"
  - "value/count"
  - "value/present"
  - "value/sum"
  - "value/sum_sqd"
  - "value/min"
  - "value/max"
  - "value/first"
dynamic_threshold: 0.01
numerical_value_threshold: 0.1

# Sharding
n_patients_per_sub_shard: null

# Misc
do_overwrite: False
do_update: True
seed: 1

# Hydra
hydra:
  job:
    name: tabularize_step_${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: ${tabularized_data_dir}/.logs/etl/${hydra.job.name}
  sweep:
    dir: ${tabularized_data_dir}/.logs/etl/${hydra.job.name}
