defaults:
  - default
  - tabularization: default
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - _self_

task_name: task

# Task cached data dir
input_dir: ${MEDS_cohort_dir}/${task_name}/task_cache
# Directory with task labels
input_label_dir: ${MEDS_cohort_dir}/${task_name}/labels
# Where to output the model and cached data
output_dir: ${MEDS_cohort_dir}/model/model_${now:%Y-%m-%d_%H-%M-%S}
output_filepath: ${output_dir}/model_metadata.parquet
cache_dir: ${MEDS_cohort_dir}/.cache

# Model parameters
model_params:
  num_boost_round: 1000
  early_stopping_rounds: 5
  model:
    booster: gbtree
    device: cpu
    nthread: 1
    tree_method: hist
    objective: binary:logistic
  iterator:
    keep_data_in_memory: True
    binarize_task: True

hydra:
  verbose: False
  sweep:
    dir: ${output_dir}/.logs/
  run:
    dir: ${output_dir}/.logs/

  # Optuna Sweeper
  sweeper:
    sampler:
      seed: 1
    study_name: null #study_${now:%Y-%m-%d_%H-%M-%S}
    storage: null
    direction: minimize
    n_trials: 10

    # Define search space for Optuna
    params:
      tabularization.window_sizes: choice([30d], [30d, 365d], [365d, full])

name: launch_xgboost
