defaults:
  - default
  - tabularization: default
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/launcher: joblib
  - _self_

task_name: task

# Task cached data dir
input_dir: ${output_cohort_dir}/${task_name}/task_cache
# Directory with task labels
input_label_dir: ${output_cohort_dir}/${task_name}/labels/
# Where to output the model and cached data
model_dir: ${output_cohort_dir}/model/model_${now:%Y-%m-%d_%H-%M-%S}
output_filepath: ${model_dir}/model_metadata.json

# Model parameters
model_params:
  epochs: 20
  early_stopping_rounds: 5
  model:
    _target_: sklearn.linear_model.SGDClassifier
    loss: log_loss
    # n_iter: ${model_params.epochs} # not sure if we want this behaviour
  iterator:
    keep_data_in_memory: True
    binarize_task: True

log_dir: ${model_dir}/.logs/

name: launch_basemodel
