defaults:
  - default
  - tabularization: default
  - imputer: default
  - normalization: default
  - model_launcher: autogluon
  - _self_

task_name: ???

# Task cached data dir
input_dir: ${output_cohort_dir}/${task_name}/task_cache
# Directory with task labels
input_label_dir: ${output_cohort_dir}/${task_name}/labels/
# Where to output the model and cached data
output_dir: ???

name: launch_autogluon

hydra:
  verbose: False
  job:
    name: MEDS_TAB_${name}_${worker}_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${model_log_dir}
  run:
    dir: ${model_log_dir}
