defaults:
  - default
  - tabularization: default
  - model_launcher: xgboost
  - override hydra/sweeper: optuna
  - override hydra/callbacks: evaluation_callback
  - override hydra/launcher: joblib
  - _self_

task_name: ???

# Directory of meds data
MEDS_cohort_dir: ???
# directory of tabularized data
tabularized_dir: ???
# Task cached data dir
input_dir: ${tabularized_dir}/${task_name}/task_cache
# Directory with task labels
input_label_dir: ???
# Where to output the model and cached data
output_model_dir: ???

output_cohort_dir: ${tabularized_dir}

delete_below_top_k: -1

name: launch_model

hydra:
  sweep:
    dir: ${output_model_dir}/sweeps/{now:%Y-%m-%d-%H-%M-%S}/
    subdir: "1"
  run:
    dir: ${path.model_log_dir}
