defaults:
  - _self_
  - default
  - tabularization: default
  - model_launcher: xgboost
  - override hydra/callbacks: evaluation_callback
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe
  - override hydra/launcher: joblib

task_name: ???

# Task cached data dir
input_dir: ${output_cohort_dir}/${task_name}/task_cache
# Directory with task labels
input_label_dir: ${output_cohort_dir}/${task_name}/labels/
# Where to output the model and cached data
output_dir: ???

delete_below_top_k: -1

name: launch_model

hydra:
  verbose: False
  job:
    name: MEDS_TAB_${name}_${worker}_${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${model_log_dir}
  run:
    dir: ${model_log_dir}
