defaults:
  - default
  - tabularization: default
  - model_launcher: xgboost
  - override hydra/sweeper: optuna
  - override hydra/callbacks: evaluation_callback
  - override hydra/launcher: joblib
  - _self_

task_name: ???

# Location of task, split, and shard specific tabularized data
input_tabularized_cache_dir: ${output_dir}/${task_name}/task_cache
# Location of  task, split, and shard specific label data
input_label_cache_dir: ${output_dir}/${task_name}/labels
# Where to output the model and cached data
output_model_dir: ???

delete_below_top_k: -1

name: launch_model

hydra:
  sweep:
    dir: ${output_model_dir}/sweeps/${now:%Y-%m-%d-%H-%M-%S}/
    subdir: "1"
  run:
    dir: ${path.model_log_dir}
  sweeper:
    direction: "maximize"
