defaults:
  - default
  - tabularization: default
  - _self_

# Raw data
# Where the code metadata is stored
input_code_metadata_fp: ${tabularized_dir}/metadata/codes.parquet
input_dir: ${meds_dir}
output_dir: ${tabularized_dir}/tabularize

name: tabularization
