# @package _global_

model_target:
  _target_: MEDS_tabular_automl.sklearn_model.SklearnModel.initialize
  model_params: ${model_params}
  input_dir: ${input_dir}
  input_label_dir: ${input_label_dir}
  model_dir: ${model_saving.model_dir}
  model_file_stem: ${model_saving.model_file_stem}
  model_file_extension: ${model_saving.model_file_extension}
  log_dir: ${log_dir}
  cache_dir: ${cache_dir}
  imputer: ${model_params.iterator.imputer}
  normalization: ${model_params.iterator.normalization}

model_params:
  epochs: 20
  early_stopping_rounds: 5
  model:
    _target_: sklearn.neighbors.KNeighborsClassifier
    weights: "distance"
    leaf_size: 30
    p: 2
    metric: "minkowski"
  iterator:
    keep_data_in_memory: True
    binarize_task: True
    normalization: ${normalization}
    imputer: ${imputer}

hydra:
  sweeper:
    direction: maximize
    n_trials: 250
    n_jobs: 25

    params:
      model_params.model.n_neighbors: range(1, 20)
      model_params.model.weights: choice(['uniform', 'distance'])
      model_params.model.leaf_size: range(10, 50)
      model_params.model.p: choice([1, 2])
      model_params.model.metric: choice(['minkowski', 'euclidean', 'manhattan'])
      model_params.epochs: range(10, 100)
      model_params.early_stopping_rounds: range(1, 10)
