# @package _global_

model_target:
  _target_: MEDS_tabular_automl.sklearn_model.SklearnModel.initialize
  model_params: ${model_params}
  input_dir: ${input_dir}
  input_label_dir: ${input_label_dir}
  model_dir: ${model_dir}
  output_filepath: ${output_filepath}
  log_dir: ${log_dir}
  cache_dir: ${cache_dir}
  imputer: ${model_params.iterator.imputer}
  normalization: ${model_params.iterator.normalization}

model_params:
  epochs: 20
  early_stopping_rounds: 5
  model:
    _target_: sklearn.ensemble.RandomForestClassifier
    criterion: "gini"
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: "sqrt"
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: True
  iterator:
    keep_data_in_memory: True
    binarize_task: True
    normalization: ${normalization}
    imputer: ${imputer}

hydra:
  sweeper:
    params:
      model_params.model.n_estimators: range(50, 300, 50)
      model_params.model.max_depth: choice([null, 10, 20, 30, 40, 50])
      model_params.model.min_samples_split: range(2, 11)
      model_params.model.min_samples_leaf: range(1, 5)
      model_params.model.max_features: choice(['sqrt', 'log2', null])
      model_params.model.bootstrap: choice([True, False])
      model_params.model.criterion: choice(['gini', 'entropy'])
      model_params.epochs: range(10, 100)
      model_params.early_stopping_rounds: range(1, 10)
