# @package _global_

model_target:
  _target_: MEDS_tabular_automl.sklearn_model.SklearnModel.initialize
  model_params: ${model_params}
  input_dir: ${input_dir}
  input_label_dir: ${input_label_dir}
  model_dir: ${model_dir}
  output_filepath: ${output_filepath}
  log_dir: ${log_dir}
  cache_dir: ${cache_dir}

model_params:
  epochs: 20
  early_stopping_rounds: 5
  model:
    _target_: sklearn.linear_model.SGDClassifier
    loss: log_loss
  iterator:
    keep_data_in_memory: True
    binarize_task: True

hydra:
  sweeper:
    params:
      +model_params.model.alpha: tag(log, interval(1e-6, 1))
      +model_params.model.l1_ratio: interval(0, 1)
      +model_params.model.penalty: choice(['l1', 'l2', 'elasticnet'])
      model_params.epochs: range(10, 100)
      model_params.early_stopping_rounds: range(1, 10)
